language: minimal

# easy way to get your local config: cat ${HOME}/.kube/config | base64 | pbcopy
env:
  global:
    - DOCKER_PUBLIC_USERNAME=openstad
    - DOCKER_IMAGE_NAME=auth
    - K8S_DEPLOYMENT_NAME=openstad-auth
    - K8S_NAMESPACE=openstad

services:
  - docker

before_install:
  - echo ${DOCKER_PUBLIC_USERNAME}
  - echo "$DOCKER_PUBLIC_USERNAME"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
  - echo ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
  - docker build -t ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} .

script:
  - docker run -e CI=true ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} env npm run test-cert -- --coverage

deploy:
  # what branches to deploy automatically
  - provider: script
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      - docker push ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - sudo mv ./kubectl /usr/local/bin/kubectl
      - mkdir ${HOME}/.kube
      - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
      - kubectl set image deployment/${K8S_DEPLOYMENT_NAME} ${K8S_DEPLOYMENT_NAME}=${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} --record -n ${K8S_NAMESPACE}
      - echo ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(feature/docker-travis|development|release)$
  # master automatically pushes new docker container with latest tag to docker
