---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.admin.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  cookieSecret: {{ .Values.admin.secrets.cookieSecret | default (randAlphaNum 32) | b64enc }}
  apiKey: {{ .Values.admin.secrets.apiKey | default (randAlphaNum 32) | b64enc }}
